evmar/n2

src/depfile.rs, src/scanner.rs
The build.ninja.d written by gn for the llvm/gn build dir
on my linux box just ends without a newline after its (only) line.
=> allow depfiles to not have a newline after the final line

src/task.rs
while comparing syscall traces between ninja and n2, i noticed that
n2 tried to launch `sh` at every entry in my PATH.
---
Not sure if this was intentional previously. But seems bad for build determinism to rely on env vars such as PATH to decide which build commands to run, so maybe it was unintentional?
=> launch sh via absolute path /bin/sh

Cargo.toml, src/lib.rs
Fixes https://github.com/evmar/n2/issues/19
I don't really know the performance implications of this, but as mentioned in the issue, the intention might have been to not use jemalloc on Windows anyway, and it might be a smaller perf gain than it was when introduced.
=> Disable jemalloc on Windows

Cargo.lock, Cargo.toml, src/lib.rs, src/task.rs, tests/basic.rs
Fixes an fd leak on all unix systems that don't have pipe2.
As of today, that's all unix systems that are not dragonfly bsd,
freebsd, linux, netbsd, openbsd, or redox -- in particular, macOS.
Fixes #14.
=> guard process creation with a mutex

src/progress.rs, src/work.rs
Fixes a TODO around the progress API in the presence of keep-going flag.
Instead of two separate calls for task state change and task completion,
there's now one shared call for task start and finish, and it takes the
full TaskResult struct as a param.  This lets progress see the 'interrupted'
state of the task.
=> refactor progress around task completion

src/parse.rs
This is crucial to support Windows. Since I'm not that familiar with the Ninja syntax, I don't really know how to test this in depth.
I have only changed the `parse_defaults` to using CRLF and tested it on the CMake Ninja test file, which at least doesn't fail because of CRLF anymore 😉
=> Add support for CRLF files

README.md, src/run.rs
On Windows the Symlink and therefore also the `file_name()` is called `ninja.exe`
=> Support "fake ninja compat" on Windows

src/canon.rs
I also changed the tests, so that they test for both path separators.
@evmar  FYI: This was the final blocker for successfully building CMake on Windows with CMake + n2 😄 
However I still need to find out, why it is re-running CMake every time, even if nothing has changed... Or is this normal?
=> Implement canon_path_in_place for backslashes

src/task.rs
This should fix https://github.com/evmar/n2/issues/48
Also fix a nearby typo paralllelism -> parallelism
=> Fixing acquiring ThreadIds when extending the vector

src/depfile.rs
When using CMake with CUDA targets, CMake adds an extra space for some reason: https://github.com/travbid/n2-cuda/blob/c152b2ffebaef90c03e45ea04dae2ef5d4299085/build/CMakeFiles/foo.dir/foo.cu.o.d#L1
(generated with CMake 3.20.4 on Ubuntu)
This causes n2 to fail during build:
```bash
~/Projects/n2-cuda/build$ n2
Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/travers/Projects/n2-cuda/build
failed: Building CUDA object CMakeFiles/foo.dir/foo.cu.o
parse error: expected ':', got ' '
CMakeFiles/foo.dir/foo.cu.o.d:1: CMakeFiles/foo.dir/foo.cu.o : ../foo.cu ...
^
```
Ninja doesn't have an issue with these spaces - should n2 also handle them, or would you prefer this to be fixed in CMake?
=> Skip spaces between target and colon in depfile

src/main.rs, src/run.rs, tests/basic.rs
1. Print errors to stderr instead of stdout
2. React to `--version` even when running outside of ninja compatibility mode. In this case, report the actual version taken from `Cargo.toml`
It is also possible to switch to a fancy [`ExitCode`](https://doc.rust-lang.org/1.61.0/std/process/struct.ExitCode.html), which can be returned from `main()` instead of having to call `std::process::exit(status_code)`, but that would mean bumping MSRV from 1.59 to 1.61, so ...
=> Minor CLI improvements

src/db.rs
When I run `cargo clippy`, I met below:
```
error: calling `set_len()` immediately after reserving a buffer creates uninitialized values
--> src/db.rs:210:9
|
210 |         let mut buf = Vec::with_capacity(len);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
214 |         unsafe { buf.set_len(len) };
|                  ^^^^^^^^^^^^^^^^
|
= help: initialize the buffer or wrap the content in `MaybeUninit`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninit_vec
= note: `#[deny(clippy::uninit_vec)]` on by default
```
This PR fixes it.
=> fix clippy: UB

src/terminal.rs
The terminal sequences appear not to be processed (at least on Windows 10) without this.
=> Allow clearing the screen on Windows too

src/process_posix.rs
* The posix_spawn_* family of functions returns != 0 on error, and the return is an error code that can be passed to strerror(). So check for `!= 0`, not `< 0`. (Error codes that can be passed to strerror() are in practice > 0!) Rename `check_posix` to `check_posix_spawn` too, to make it clear it's only for checking return codes from functions in the posix_spawn_* family.
* The normal C runtime functions return a code < 0 on error, and put the error code in errno. Add a check_ret_errno function and call that instead of check_posix for non-spawn functions.
=> Improve error printing in process_posix.rs

src/progress.rs
thread '<unnamed>' panicked at 'byte index 78 is not a char boundary; it is inside '━' (bytes 77..80) of `     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 KB 3.6 MB/s eta 0:00:00`', src/progress.rs:330:22
=> Fix a panic when truncating inside a unicode char

src/graph.rs, src/load.rs, src/parse.rs, src/work.rs, tests/e2e/mod.rs, tests/e2e/validations.rs
These were added to regular ninja in:
https://github.com/ninja-build/ninja/commit/04c410b15b70fb321928ffba19d697db15cb0121
Android uses them, so they're needed to port android to n2. (which is something I'm exploring but not committing to)
=> Add validation inputs

src/canon.rs, tests/e2e/directories.rs, tests/e2e/mod.rs
It's possible to have a ninja dep on '.', meaning the directory that ninja was run from. Previously, canon_path_fast would canonicalize this to an empty string, which would cause stats and other opterations to fail.
This was found when running the android codebase with n2.
=> Canonicalize paths to '.' instead of an empty string

tests/e2e/validations.rs
The test is supposed to ensure that out builds before validation_input.
For #102
=> Wait for out instead of regular_input

benches/parse.rs, src/eval.rs, src/lib.rs, src/load.rs, src/parse.rs, src/scanner.rs, tests/e2e/basic.rs
This fixes an incompatibility with ninja.
I've also refactored Env to make it clearer and remove the TODO(#83), but I actually think we could do signifigant further cleanup. Only rules should require EvalStrings, global variables and build bindings can be evaluated as soon as they're read, although maybe that would change with subninjas. Also, rules currently parse their variables as EvalString<String>, but I think that could be changed to EvalString<&'text str> if we hold onto the byte buffers of all the included files until the parsing is done.
Fixes #91 and #39.
=> Evaluate build paths in the context of the build's bindings

Cargo.lock, Cargo.toml, benches/parse.rs, src/eval.rs, src/graph.rs, src/load.rs, src/parse.rs, src/work.rs
- Pass owned strings to id_from_canonical instead of references
- Precalculate the length of evaluated strings, and reserve space in the result string
- Only hash strings once in id_from_canonical
- Switch some HashMaps to FxHashMaps
These changes give about a 20% performance improvement to bench_load_synthetic, and save a couple seconds off of loading the android ninja files. Most of this is from the switch to FxHashMap, the other changes are only around a 5% improvement.
If you have concerns about any of these commits let me know and I'll take those ones out of the PR.
=> Minor performance improvements

src/depfile.rs, src/smallmap.rs, src/task.rs, tests/e2e/discovered.rs
This is needed for android. It just treats all the deps of all targets in the depfile as deps for the Build.
In task.rs there is a TODO to verify that the targets refer to the outputs of the Build, but adding that verification breaks the android build. In android's case, there are some depfiles that contain `foo.o: path/to/some/dep.asm` where it should instead be `path/to/foo.o: path/to/some/dep.asm`.
With this change, you can do a full build of android with n2.
=> Parse depfiles with multiple targets

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, tests/e2e/mod.rs
Android doesn't have the filetime crate vendored into the tree, but as of rust 1.75, the standard library has the ability to change filetimes.
=> Remove dependency on filetime crate

src/signal.rs
Atomics in Rust posses "interior mutability", which means that you can change their contents through a `&` without a need for a `&mut`. `load`/`store` do indeed take a `&`.
So the `static` does not have to be `mut`. And as soon as it isn't, taking references to it becomes completely safe. Yay.
=> Atomic operations are safe actually

src/canon.rs
The previously present `MaybeUninit::uninit().assume_init()` actually desugared to `MaybeUninit::<[MaybeUninit<T>; 60]>::uninit().assume_init()`. This is probably not UB, but there's a more idiomatic and 100% safe way to do the same thing.
=> `[MaybeUninit<T>; N]` creation is safe

Cargo.toml, src/lib.rs
I wanted to leverage the n2 parser in Rust without jemalloc set as the global allocator.
=> Move jemalloc to crate feature to make it optional
